import { useRef, useState } from "react";
import { Float, useGLTF, useTexture } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";

const Cube = (props) => {
  const { nodes, materials } = useGLTF("/models/rubiks_cube (1).glb");
  const cubeRef = useRef();
  const [hovered, setHovered] = useState(false);

  useGSAP(() => {
    gsap
      .timeline({
        repeat: -1,
        repeatDelay: 0.5,
      })
      .to(cubeRef.current.rotation, {
        y: hovered ? "+=2" : `+=${Math.PI * 2}`,
        x: hovered ? "+=2" : `-=${Math.PI * 2}`,
        duration: 2.5,
        stagger: {
          each: 0.15,
        },
      });
  });
  return (
    <Float floatIntensity={2}>
      <group
        position={[9, -6, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.01057}
        dispose={null}
        {...props}
        ref={cubeRef}
        onPointerOver={(e) => setHovered(true)}
      >
        <group scale={0.209}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rubik_Material001_0.geometry}
            material={materials["Material.001"]}
          />
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["1_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["1_Blue_0"].geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["1_Yellow_0"].geometry}
              material={materials.Yellow}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["1_Orange_0"].geometry}
              material={materials.Orange}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["2_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["2_Yellow_0"].geometry}
              material={materials.Yellow}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["2_Orange_0"].geometry}
              material={materials.Orange}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["3_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["3_Green_0"].geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["3_Orange_0"].geometry}
              material={materials.Orange}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["3_Yellow_0"].geometry}
              material={materials.Yellow}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["4_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["4_Blue_0"].geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["4_Yellow_0"].geometry}
              material={materials.Yellow}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["5_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["5_Green_0"].geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["5_Yellow_0"].geometry}
              material={materials.Yellow}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["6_Red_0"].geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["6_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["6_Green_0"].geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["6_Yellow_0"].geometry}
              material={materials.Yellow}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["7_Red_0"].geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["7_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["7_Blue_0"].geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["7_Yellow_0"].geometry}
              material={materials.Yellow}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["8_Yellow_0"].geometry}
              material={materials.Yellow}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["8_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["8_Red_0"].geometry}
              material={materials.material}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["9_Yellow_0"].geometry}
              material={materials.Yellow}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["9_Black_0"].geometry}
              material={materials.Black}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["10_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["10_White_0"].geometry}
              material={materials.White}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["10_Red_0"].geometry}
              material={materials.material}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["11_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["11_Green_0"].geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["11_White_0"].geometry}
              material={materials.White}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["11_Red_0"].geometry}
              material={materials.material}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["12_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["12_Blue_0"].geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["12_White_0"].geometry}
              material={materials.White}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["12_Orange_0"].geometry}
              material={materials.Orange}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["13_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["13_White_0"].geometry}
              material={materials.White}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["13_Orange_0"].geometry}
              material={materials.Orange}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["14_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["14_Green_0"].geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["14_Orange_0"].geometry}
              material={materials.Orange}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["14_White_0"].geometry}
              material={materials.White}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["15_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["15_Blue_0"].geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["15_White_0"].geometry}
              material={materials.White}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["16_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["16_Blue_0"].geometry}
              material={materials.Blue}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["17_Red_0"].geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["17_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["17_Blue_0"].geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["17_White_0"].geometry}
              material={materials.White}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["18_Green_0"].geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["18_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["18_White_0"].geometry}
              material={materials.White}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["19_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["19_White_0"].geometry}
              material={materials.White}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["20_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["20_Red_0"].geometry}
              material={materials.material}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["21_Green_0"].geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["21_Black_0"].geometry}
              material={materials.Black}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["22_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["22_Orange_0"].geometry}
              material={materials.Orange}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["23_Red_0"].geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["23_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["23_Blue_0"].geometry}
              material={materials.Blue}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["24_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["24_Blue_0"].geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["24_Orange_0"].geometry}
              material={materials.Orange}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["25_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["25_Red_0"].geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["25_Green_0"].geometry}
              material={materials.Green}
            />
          </group>
          <group scale={2.383}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["26_Orange_0"].geometry}
              material={materials.Orange}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["26_Black_0"].geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["26_Green_0"].geometry}
              material={materials.Green}
            />
          </group>
        </group>
      </group>
    </Float>
  );
};

useGLTF.preload("/models/rubiks_cube (1).glb");

export default Cube;
